# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b70e484e49bd44183f2973ea7a67717573138d725a4e862d5ec17b9cacb4b72405400eb55a4c6b97af1fd5e29f5245e7b1688079867b4a0e6f50ef721037b6b

test:
  secret_key_base: f8257bb6209ce6167cbc91c247a8c09eecb15f809d6ecb3c2c4ebd465f3534d7e6ab399bc4dc4c6470b796169ec96fa58fa3ea718f3732c4f34b3b7e6552a461

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
